/*
 * generated by Xtext 2.25.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FactoryLogicLangStandaloneSetup extends FactoryLogicLangStandaloneSetupGenerated {

	public static void doSetup() {
		new FactoryLogicLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
