/*
 * generated by Xtext 2.25.0
 */
package xtext.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import xtext.parser.antlr.internal.InternalFactoryLogicLangParser;

public class FactoryLogicLangTokenSource extends AbstractIndentationTokenSource {

	public FactoryLogicLangTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalFactoryLogicLangParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalFactoryLogicLangParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalFactoryLogicLangParser.RULE_END;
	}

}
