/*
 * generated by Xtext 2.25.0
 */
package xtext.factoryLang.ide


/**
 * Use this class to register ide components.
 */
class FactoryLangIdeModule extends AbstractFactoryLangIdeModule {
}
