/*
 * generated by Xtext 2.25.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FactoryLogicLangUiModule extends AbstractFactoryLogicLangUiModule {

	public FactoryLogicLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
