/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getConditional()
 * @model
 * @generated
 */
public interface Conditional extends Declaration
{
} // Conditional
