/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xtext.factoryLogicLang.FactoryLogicLangFactory
 * @model kind="package"
 * @generated
 */
public interface FactoryLogicLangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "factoryLogicLang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http:www.FactoryLogicLang.xtext";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "factoryLogicLang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FactoryLogicLangPackage eINSTANCE = xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl.init();

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.ModelImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DECLARATIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.DeclarationImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.DeviceImpl <em>Device</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.DeviceImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getDevice()
   * @generated
   */
  int DEVICE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Device</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.CraneImpl <em>Crane</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.CraneImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCrane()
   * @generated
   */
  int CRANE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE__NAME = DEVICE__NAME;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE__PARAMETERS = DEVICE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Crane</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_FEATURE_COUNT = DEVICE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.CraneParameterImpl <em>Crane Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.CraneParameterImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCraneParameter()
   * @generated
   */
  int CRANE_PARAMETER = 4;

  /**
   * The feature id for the '<em><b>Degree</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_PARAMETER__DEGREE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_PARAMETER__NAME = 1;

  /**
   * The number of structural features of the '<em>Crane Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_PARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.StorageImpl <em>Storage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.StorageImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorage()
   * @generated
   */
  int STORAGE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE__NAME = DEVICE__NAME;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE__PARAMETERS = DEVICE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Storage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_FEATURE_COUNT = DEVICE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.StorageParameterImpl <em>Storage Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.StorageParameterImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorageParameter()
   * @generated
   */
  int STORAGE_PARAMETER = 6;

  /**
   * The number of structural features of the '<em>Storage Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_PARAMETER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.StorageSlotParameterImpl <em>Storage Slot Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.StorageSlotParameterImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorageSlotParameter()
   * @generated
   */
  int STORAGE_SLOT_PARAMETER = 7;

  /**
   * The feature id for the '<em><b>Slots</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_SLOT_PARAMETER__SLOTS = STORAGE_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Storage Slot Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_SLOT_PARAMETER_FEATURE_COUNT = STORAGE_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.StoragePositionParameterImpl <em>Storage Position Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.StoragePositionParameterImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStoragePositionParameter()
   * @generated
   */
  int STORAGE_POSITION_PARAMETER = 8;

  /**
   * The feature id for the '<em><b>Slot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_POSITION_PARAMETER__SLOT = STORAGE_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_POSITION_PARAMETER__NAME = STORAGE_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Storage Position Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_POSITION_PARAMETER_FEATURE_COUNT = STORAGE_PARAMETER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.CameraImpl <em>Camera</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.CameraImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCamera()
   * @generated
   */
  int CAMERA = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA__NAME = DEVICE__NAME;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA__PARAMETERS = DEVICE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Camera</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_FEATURE_COUNT = DEVICE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.CameraParameterImpl <em>Camera Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.CameraParameterImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCameraParameter()
   * @generated
   */
  int CAMERA_PARAMETER = 10;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_PARAMETER__COLOR = 0;

  /**
   * The number of structural features of the '<em>Camera Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.LogicImpl <em>Logic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.LogicImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getLogic()
   * @generated
   */
  int LOGIC = 11;

  /**
   * The number of structural features of the '<em>Logic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.ConditionalImpl <em>Conditional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.ConditionalImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getConditional()
   * @generated
   */
  int CONDITIONAL = 12;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__VARIABLE = LOGIC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__SOURCE = LOGIC_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__OPERATOR = LOGIC_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Comparison const</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__COMPARISON_CONST = LOGIC_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Comparison color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__COMPARISON_COLOR = LOGIC_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Comparison int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__COMPARISON_INT = LOGIC_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Logics</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__LOGICS = LOGIC_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Conditional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_FEATURE_COUNT = LOGIC_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.LoopImpl <em>Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.LoopImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getLoop()
   * @generated
   */
  int LOOP = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__NAME = LOGIC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__LIST = LOGIC_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__SOURCE = LOGIC_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__OPERATOR = LOGIC_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Comparison const</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__COMPARISON_CONST = LOGIC_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Comparison color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__COMPARISON_COLOR = LOGIC_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Comparison int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__COMPARISON_INT = LOGIC_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Logics</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__LOGICS = LOGIC_FEATURE_COUNT + 7;

  /**
   * The number of structural features of the '<em>Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_FEATURE_COUNT = LOGIC_FEATURE_COUNT + 8;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.OperationImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 14;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = LOGIC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.StorageMoveEmptySlotImpl <em>Storage Move Empty Slot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.StorageMoveEmptySlotImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorageMoveEmptySlot()
   * @generated
   */
  int STORAGE_MOVE_EMPTY_SLOT = 15;

  /**
   * The feature id for the '<em><b>Device</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MOVE_EMPTY_SLOT__DEVICE = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MOVE_EMPTY_SLOT__DESTINATION = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Storage Move Empty Slot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MOVE_EMPTY_SLOT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.StorageMoveSlotImpl <em>Storage Move Slot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.StorageMoveSlotImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorageMoveSlot()
   * @generated
   */
  int STORAGE_MOVE_SLOT = 16;

  /**
   * The feature id for the '<em><b>Device</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MOVE_SLOT__DEVICE = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Position</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MOVE_SLOT__POSITION = OPERATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MOVE_SLOT__DESTINATION = OPERATION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Storage Move Slot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MOVE_SLOT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.StorageMarkSlotImpl <em>Storage Mark Slot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.StorageMarkSlotImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorageMarkSlot()
   * @generated
   */
  int STORAGE_MARK_SLOT = 17;

  /**
   * The feature id for the '<em><b>Device</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MARK_SLOT__DEVICE = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Position</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MARK_SLOT__POSITION = OPERATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Comparison const</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MARK_SLOT__COMPARISON_CONST = OPERATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Comparison color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MARK_SLOT__COMPARISON_COLOR = OPERATION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Comparison int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MARK_SLOT__COMPARISON_INT = OPERATION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MARK_SLOT__QUANTITY = OPERATION_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Measure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MARK_SLOT__MEASURE = OPERATION_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Storage Mark Slot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_MARK_SLOT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.CameraScanImpl <em>Camera Scan</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.CameraScanImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCameraScan()
   * @generated
   */
  int CAMERA_SCAN = 18;

  /**
   * The feature id for the '<em><b>Device</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_SCAN__DEVICE = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_SCAN__NAME = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Camera Scan</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_SCAN_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.CranePickupImpl <em>Crane Pickup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.CranePickupImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCranePickup()
   * @generated
   */
  int CRANE_PICKUP = 19;

  /**
   * The feature id for the '<em><b>Device</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_PICKUP__DEVICE = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Location</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_PICKUP__LOCATION = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Crane Pickup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_PICKUP_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.impl.CraneDropImpl <em>Crane Drop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.impl.CraneDropImpl
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCraneDrop()
   * @generated
   */
  int CRANE_DROP = 20;

  /**
   * The feature id for the '<em><b>Device</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_DROP__DEVICE = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Location</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_DROP__LOCATION = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Crane Drop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_DROP_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.COLOR <em>COLOR</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.COLOR
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCOLOR()
   * @generated
   */
  int COLOR = 21;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.CONST_VARIABLES <em>CONST VARIABLES</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.CONST_VARIABLES
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCONST_VARIABLES()
   * @generated
   */
  int CONST_VARIABLES = 22;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.BOOLEAN_OPERATOR <em>BOOLEAN OPERATOR</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.BOOLEAN_OPERATOR
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getBOOLEAN_OPERATOR()
   * @generated
   */
  int BOOLEAN_OPERATOR = 23;

  /**
   * The meta object id for the '{@link xtext.factoryLogicLang.TIME <em>TIME</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLogicLang.TIME
   * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getTIME()
   * @generated
   */
  int TIME = 24;


  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see xtext.factoryLogicLang.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLogicLang.Model#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see xtext.factoryLogicLang.Model#getDeclarations()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Declarations();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see xtext.factoryLogicLang.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.Device <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device</em>'.
   * @see xtext.factoryLogicLang.Device
   * @generated
   */
  EClass getDevice();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Device#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.factoryLogicLang.Device#getName()
   * @see #getDevice()
   * @generated
   */
  EAttribute getDevice_Name();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.Crane <em>Crane</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Crane</em>'.
   * @see xtext.factoryLogicLang.Crane
   * @generated
   */
  EClass getCrane();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLogicLang.Crane#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see xtext.factoryLogicLang.Crane#getParameters()
   * @see #getCrane()
   * @generated
   */
  EReference getCrane_Parameters();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.CraneParameter <em>Crane Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Crane Parameter</em>'.
   * @see xtext.factoryLogicLang.CraneParameter
   * @generated
   */
  EClass getCraneParameter();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.CraneParameter#getDegree <em>Degree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Degree</em>'.
   * @see xtext.factoryLogicLang.CraneParameter#getDegree()
   * @see #getCraneParameter()
   * @generated
   */
  EAttribute getCraneParameter_Degree();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.CraneParameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.factoryLogicLang.CraneParameter#getName()
   * @see #getCraneParameter()
   * @generated
   */
  EAttribute getCraneParameter_Name();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.Storage <em>Storage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Storage</em>'.
   * @see xtext.factoryLogicLang.Storage
   * @generated
   */
  EClass getStorage();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLogicLang.Storage#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see xtext.factoryLogicLang.Storage#getParameters()
   * @see #getStorage()
   * @generated
   */
  EReference getStorage_Parameters();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.StorageParameter <em>Storage Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Storage Parameter</em>'.
   * @see xtext.factoryLogicLang.StorageParameter
   * @generated
   */
  EClass getStorageParameter();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.StorageSlotParameter <em>Storage Slot Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Storage Slot Parameter</em>'.
   * @see xtext.factoryLogicLang.StorageSlotParameter
   * @generated
   */
  EClass getStorageSlotParameter();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.StorageSlotParameter#getSlots <em>Slots</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Slots</em>'.
   * @see xtext.factoryLogicLang.StorageSlotParameter#getSlots()
   * @see #getStorageSlotParameter()
   * @generated
   */
  EAttribute getStorageSlotParameter_Slots();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.StoragePositionParameter <em>Storage Position Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Storage Position Parameter</em>'.
   * @see xtext.factoryLogicLang.StoragePositionParameter
   * @generated
   */
  EClass getStoragePositionParameter();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.StoragePositionParameter#getSlot <em>Slot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Slot</em>'.
   * @see xtext.factoryLogicLang.StoragePositionParameter#getSlot()
   * @see #getStoragePositionParameter()
   * @generated
   */
  EAttribute getStoragePositionParameter_Slot();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.StoragePositionParameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.factoryLogicLang.StoragePositionParameter#getName()
   * @see #getStoragePositionParameter()
   * @generated
   */
  EAttribute getStoragePositionParameter_Name();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.Camera <em>Camera</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Camera</em>'.
   * @see xtext.factoryLogicLang.Camera
   * @generated
   */
  EClass getCamera();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLogicLang.Camera#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see xtext.factoryLogicLang.Camera#getParameters()
   * @see #getCamera()
   * @generated
   */
  EReference getCamera_Parameters();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.CameraParameter <em>Camera Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Camera Parameter</em>'.
   * @see xtext.factoryLogicLang.CameraParameter
   * @generated
   */
  EClass getCameraParameter();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.CameraParameter#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see xtext.factoryLogicLang.CameraParameter#getColor()
   * @see #getCameraParameter()
   * @generated
   */
  EAttribute getCameraParameter_Color();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.Logic <em>Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic</em>'.
   * @see xtext.factoryLogicLang.Logic
   * @generated
   */
  EClass getLogic();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.Conditional <em>Conditional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional</em>'.
   * @see xtext.factoryLogicLang.Conditional
   * @generated
   */
  EClass getConditional();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Conditional#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see xtext.factoryLogicLang.Conditional#getVariable()
   * @see #getConditional()
   * @generated
   */
  EAttribute getConditional_Variable();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.Conditional#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see xtext.factoryLogicLang.Conditional#getSource()
   * @see #getConditional()
   * @generated
   */
  EReference getConditional_Source();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Conditional#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see xtext.factoryLogicLang.Conditional#getOperator()
   * @see #getConditional()
   * @generated
   */
  EAttribute getConditional_Operator();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Conditional#getComparison_const <em>Comparison const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison const</em>'.
   * @see xtext.factoryLogicLang.Conditional#getComparison_const()
   * @see #getConditional()
   * @generated
   */
  EAttribute getConditional_Comparison_const();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Conditional#getComparison_color <em>Comparison color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison color</em>'.
   * @see xtext.factoryLogicLang.Conditional#getComparison_color()
   * @see #getConditional()
   * @generated
   */
  EAttribute getConditional_Comparison_color();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Conditional#getComparison_int <em>Comparison int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison int</em>'.
   * @see xtext.factoryLogicLang.Conditional#getComparison_int()
   * @see #getConditional()
   * @generated
   */
  EAttribute getConditional_Comparison_int();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLogicLang.Conditional#getLogics <em>Logics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Logics</em>'.
   * @see xtext.factoryLogicLang.Conditional#getLogics()
   * @see #getConditional()
   * @generated
   */
  EReference getConditional_Logics();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.Loop <em>Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop</em>'.
   * @see xtext.factoryLogicLang.Loop
   * @generated
   */
  EClass getLoop();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Loop#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.factoryLogicLang.Loop#getName()
   * @see #getLoop()
   * @generated
   */
  EAttribute getLoop_Name();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Loop#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>List</em>'.
   * @see xtext.factoryLogicLang.Loop#getList()
   * @see #getLoop()
   * @generated
   */
  EAttribute getLoop_List();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.Loop#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see xtext.factoryLogicLang.Loop#getSource()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Source();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Loop#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see xtext.factoryLogicLang.Loop#getOperator()
   * @see #getLoop()
   * @generated
   */
  EAttribute getLoop_Operator();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Loop#getComparison_const <em>Comparison const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison const</em>'.
   * @see xtext.factoryLogicLang.Loop#getComparison_const()
   * @see #getLoop()
   * @generated
   */
  EAttribute getLoop_Comparison_const();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Loop#getComparison_color <em>Comparison color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison color</em>'.
   * @see xtext.factoryLogicLang.Loop#getComparison_color()
   * @see #getLoop()
   * @generated
   */
  EAttribute getLoop_Comparison_color();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.Loop#getComparison_int <em>Comparison int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison int</em>'.
   * @see xtext.factoryLogicLang.Loop#getComparison_int()
   * @see #getLoop()
   * @generated
   */
  EAttribute getLoop_Comparison_int();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLogicLang.Loop#getLogics <em>Logics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Logics</em>'.
   * @see xtext.factoryLogicLang.Loop#getLogics()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Logics();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see xtext.factoryLogicLang.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.StorageMoveEmptySlot <em>Storage Move Empty Slot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Storage Move Empty Slot</em>'.
   * @see xtext.factoryLogicLang.StorageMoveEmptySlot
   * @generated
   */
  EClass getStorageMoveEmptySlot();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.StorageMoveEmptySlot#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Device</em>'.
   * @see xtext.factoryLogicLang.StorageMoveEmptySlot#getDevice()
   * @see #getStorageMoveEmptySlot()
   * @generated
   */
  EReference getStorageMoveEmptySlot_Device();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.StorageMoveEmptySlot#getDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Destination</em>'.
   * @see xtext.factoryLogicLang.StorageMoveEmptySlot#getDestination()
   * @see #getStorageMoveEmptySlot()
   * @generated
   */
  EReference getStorageMoveEmptySlot_Destination();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.StorageMoveSlot <em>Storage Move Slot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Storage Move Slot</em>'.
   * @see xtext.factoryLogicLang.StorageMoveSlot
   * @generated
   */
  EClass getStorageMoveSlot();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.StorageMoveSlot#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Device</em>'.
   * @see xtext.factoryLogicLang.StorageMoveSlot#getDevice()
   * @see #getStorageMoveSlot()
   * @generated
   */
  EReference getStorageMoveSlot_Device();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.StorageMoveSlot#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Position</em>'.
   * @see xtext.factoryLogicLang.StorageMoveSlot#getPosition()
   * @see #getStorageMoveSlot()
   * @generated
   */
  EReference getStorageMoveSlot_Position();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.StorageMoveSlot#getDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Destination</em>'.
   * @see xtext.factoryLogicLang.StorageMoveSlot#getDestination()
   * @see #getStorageMoveSlot()
   * @generated
   */
  EReference getStorageMoveSlot_Destination();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.StorageMarkSlot <em>Storage Mark Slot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Storage Mark Slot</em>'.
   * @see xtext.factoryLogicLang.StorageMarkSlot
   * @generated
   */
  EClass getStorageMarkSlot();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.StorageMarkSlot#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Device</em>'.
   * @see xtext.factoryLogicLang.StorageMarkSlot#getDevice()
   * @see #getStorageMarkSlot()
   * @generated
   */
  EReference getStorageMarkSlot_Device();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.StorageMarkSlot#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Position</em>'.
   * @see xtext.factoryLogicLang.StorageMarkSlot#getPosition()
   * @see #getStorageMarkSlot()
   * @generated
   */
  EReference getStorageMarkSlot_Position();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.StorageMarkSlot#getComparison_const <em>Comparison const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison const</em>'.
   * @see xtext.factoryLogicLang.StorageMarkSlot#getComparison_const()
   * @see #getStorageMarkSlot()
   * @generated
   */
  EAttribute getStorageMarkSlot_Comparison_const();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.StorageMarkSlot#getComparison_color <em>Comparison color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison color</em>'.
   * @see xtext.factoryLogicLang.StorageMarkSlot#getComparison_color()
   * @see #getStorageMarkSlot()
   * @generated
   */
  EAttribute getStorageMarkSlot_Comparison_color();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.StorageMarkSlot#getComparison_int <em>Comparison int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison int</em>'.
   * @see xtext.factoryLogicLang.StorageMarkSlot#getComparison_int()
   * @see #getStorageMarkSlot()
   * @generated
   */
  EAttribute getStorageMarkSlot_Comparison_int();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.StorageMarkSlot#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantity</em>'.
   * @see xtext.factoryLogicLang.StorageMarkSlot#getQuantity()
   * @see #getStorageMarkSlot()
   * @generated
   */
  EAttribute getStorageMarkSlot_Quantity();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.StorageMarkSlot#getMeasure <em>Measure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Measure</em>'.
   * @see xtext.factoryLogicLang.StorageMarkSlot#getMeasure()
   * @see #getStorageMarkSlot()
   * @generated
   */
  EAttribute getStorageMarkSlot_Measure();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.CameraScan <em>Camera Scan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Camera Scan</em>'.
   * @see xtext.factoryLogicLang.CameraScan
   * @generated
   */
  EClass getCameraScan();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.CameraScan#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Device</em>'.
   * @see xtext.factoryLogicLang.CameraScan#getDevice()
   * @see #getCameraScan()
   * @generated
   */
  EReference getCameraScan_Device();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLogicLang.CameraScan#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.factoryLogicLang.CameraScan#getName()
   * @see #getCameraScan()
   * @generated
   */
  EAttribute getCameraScan_Name();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.CranePickup <em>Crane Pickup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Crane Pickup</em>'.
   * @see xtext.factoryLogicLang.CranePickup
   * @generated
   */
  EClass getCranePickup();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.CranePickup#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Device</em>'.
   * @see xtext.factoryLogicLang.CranePickup#getDevice()
   * @see #getCranePickup()
   * @generated
   */
  EReference getCranePickup_Device();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.CranePickup#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Location</em>'.
   * @see xtext.factoryLogicLang.CranePickup#getLocation()
   * @see #getCranePickup()
   * @generated
   */
  EReference getCranePickup_Location();

  /**
   * Returns the meta object for class '{@link xtext.factoryLogicLang.CraneDrop <em>Crane Drop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Crane Drop</em>'.
   * @see xtext.factoryLogicLang.CraneDrop
   * @generated
   */
  EClass getCraneDrop();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.CraneDrop#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Device</em>'.
   * @see xtext.factoryLogicLang.CraneDrop#getDevice()
   * @see #getCraneDrop()
   * @generated
   */
  EReference getCraneDrop_Device();

  /**
   * Returns the meta object for the reference '{@link xtext.factoryLogicLang.CraneDrop#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Location</em>'.
   * @see xtext.factoryLogicLang.CraneDrop#getLocation()
   * @see #getCraneDrop()
   * @generated
   */
  EReference getCraneDrop_Location();

  /**
   * Returns the meta object for enum '{@link xtext.factoryLogicLang.COLOR <em>COLOR</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>COLOR</em>'.
   * @see xtext.factoryLogicLang.COLOR
   * @generated
   */
  EEnum getCOLOR();

  /**
   * Returns the meta object for enum '{@link xtext.factoryLogicLang.CONST_VARIABLES <em>CONST VARIABLES</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>CONST VARIABLES</em>'.
   * @see xtext.factoryLogicLang.CONST_VARIABLES
   * @generated
   */
  EEnum getCONST_VARIABLES();

  /**
   * Returns the meta object for enum '{@link xtext.factoryLogicLang.BOOLEAN_OPERATOR <em>BOOLEAN OPERATOR</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>BOOLEAN OPERATOR</em>'.
   * @see xtext.factoryLogicLang.BOOLEAN_OPERATOR
   * @generated
   */
  EEnum getBOOLEAN_OPERATOR();

  /**
   * Returns the meta object for enum '{@link xtext.factoryLogicLang.TIME <em>TIME</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>TIME</em>'.
   * @see xtext.factoryLogicLang.TIME
   * @generated
   */
  EEnum getTIME();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FactoryLogicLangFactory getFactoryLogicLangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.ModelImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DECLARATIONS = eINSTANCE.getModel_Declarations();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.DeclarationImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.DeviceImpl <em>Device</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.DeviceImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getDevice()
     * @generated
     */
    EClass DEVICE = eINSTANCE.getDevice();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__NAME = eINSTANCE.getDevice_Name();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.CraneImpl <em>Crane</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.CraneImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCrane()
     * @generated
     */
    EClass CRANE = eINSTANCE.getCrane();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRANE__PARAMETERS = eINSTANCE.getCrane_Parameters();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.CraneParameterImpl <em>Crane Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.CraneParameterImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCraneParameter()
     * @generated
     */
    EClass CRANE_PARAMETER = eINSTANCE.getCraneParameter();

    /**
     * The meta object literal for the '<em><b>Degree</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CRANE_PARAMETER__DEGREE = eINSTANCE.getCraneParameter_Degree();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CRANE_PARAMETER__NAME = eINSTANCE.getCraneParameter_Name();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.StorageImpl <em>Storage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.StorageImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorage()
     * @generated
     */
    EClass STORAGE = eINSTANCE.getStorage();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORAGE__PARAMETERS = eINSTANCE.getStorage_Parameters();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.StorageParameterImpl <em>Storage Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.StorageParameterImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorageParameter()
     * @generated
     */
    EClass STORAGE_PARAMETER = eINSTANCE.getStorageParameter();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.StorageSlotParameterImpl <em>Storage Slot Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.StorageSlotParameterImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorageSlotParameter()
     * @generated
     */
    EClass STORAGE_SLOT_PARAMETER = eINSTANCE.getStorageSlotParameter();

    /**
     * The meta object literal for the '<em><b>Slots</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE_SLOT_PARAMETER__SLOTS = eINSTANCE.getStorageSlotParameter_Slots();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.StoragePositionParameterImpl <em>Storage Position Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.StoragePositionParameterImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStoragePositionParameter()
     * @generated
     */
    EClass STORAGE_POSITION_PARAMETER = eINSTANCE.getStoragePositionParameter();

    /**
     * The meta object literal for the '<em><b>Slot</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE_POSITION_PARAMETER__SLOT = eINSTANCE.getStoragePositionParameter_Slot();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE_POSITION_PARAMETER__NAME = eINSTANCE.getStoragePositionParameter_Name();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.CameraImpl <em>Camera</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.CameraImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCamera()
     * @generated
     */
    EClass CAMERA = eINSTANCE.getCamera();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMERA__PARAMETERS = eINSTANCE.getCamera_Parameters();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.CameraParameterImpl <em>Camera Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.CameraParameterImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCameraParameter()
     * @generated
     */
    EClass CAMERA_PARAMETER = eINSTANCE.getCameraParameter();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMERA_PARAMETER__COLOR = eINSTANCE.getCameraParameter_Color();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.LogicImpl <em>Logic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.LogicImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getLogic()
     * @generated
     */
    EClass LOGIC = eINSTANCE.getLogic();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.ConditionalImpl <em>Conditional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.ConditionalImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getConditional()
     * @generated
     */
    EClass CONDITIONAL = eINSTANCE.getConditional();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL__VARIABLE = eINSTANCE.getConditional_Variable();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL__SOURCE = eINSTANCE.getConditional_Source();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL__OPERATOR = eINSTANCE.getConditional_Operator();

    /**
     * The meta object literal for the '<em><b>Comparison const</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL__COMPARISON_CONST = eINSTANCE.getConditional_Comparison_const();

    /**
     * The meta object literal for the '<em><b>Comparison color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL__COMPARISON_COLOR = eINSTANCE.getConditional_Comparison_color();

    /**
     * The meta object literal for the '<em><b>Comparison int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL__COMPARISON_INT = eINSTANCE.getConditional_Comparison_int();

    /**
     * The meta object literal for the '<em><b>Logics</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL__LOGICS = eINSTANCE.getConditional_Logics();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.LoopImpl <em>Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.LoopImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getLoop()
     * @generated
     */
    EClass LOOP = eINSTANCE.getLoop();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOP__NAME = eINSTANCE.getLoop_Name();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOP__LIST = eINSTANCE.getLoop_List();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__SOURCE = eINSTANCE.getLoop_Source();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOP__OPERATOR = eINSTANCE.getLoop_Operator();

    /**
     * The meta object literal for the '<em><b>Comparison const</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOP__COMPARISON_CONST = eINSTANCE.getLoop_Comparison_const();

    /**
     * The meta object literal for the '<em><b>Comparison color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOP__COMPARISON_COLOR = eINSTANCE.getLoop_Comparison_color();

    /**
     * The meta object literal for the '<em><b>Comparison int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOP__COMPARISON_INT = eINSTANCE.getLoop_Comparison_int();

    /**
     * The meta object literal for the '<em><b>Logics</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__LOGICS = eINSTANCE.getLoop_Logics();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.OperationImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.StorageMoveEmptySlotImpl <em>Storage Move Empty Slot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.StorageMoveEmptySlotImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorageMoveEmptySlot()
     * @generated
     */
    EClass STORAGE_MOVE_EMPTY_SLOT = eINSTANCE.getStorageMoveEmptySlot();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORAGE_MOVE_EMPTY_SLOT__DEVICE = eINSTANCE.getStorageMoveEmptySlot_Device();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORAGE_MOVE_EMPTY_SLOT__DESTINATION = eINSTANCE.getStorageMoveEmptySlot_Destination();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.StorageMoveSlotImpl <em>Storage Move Slot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.StorageMoveSlotImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorageMoveSlot()
     * @generated
     */
    EClass STORAGE_MOVE_SLOT = eINSTANCE.getStorageMoveSlot();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORAGE_MOVE_SLOT__DEVICE = eINSTANCE.getStorageMoveSlot_Device();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORAGE_MOVE_SLOT__POSITION = eINSTANCE.getStorageMoveSlot_Position();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORAGE_MOVE_SLOT__DESTINATION = eINSTANCE.getStorageMoveSlot_Destination();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.StorageMarkSlotImpl <em>Storage Mark Slot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.StorageMarkSlotImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getStorageMarkSlot()
     * @generated
     */
    EClass STORAGE_MARK_SLOT = eINSTANCE.getStorageMarkSlot();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORAGE_MARK_SLOT__DEVICE = eINSTANCE.getStorageMarkSlot_Device();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORAGE_MARK_SLOT__POSITION = eINSTANCE.getStorageMarkSlot_Position();

    /**
     * The meta object literal for the '<em><b>Comparison const</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE_MARK_SLOT__COMPARISON_CONST = eINSTANCE.getStorageMarkSlot_Comparison_const();

    /**
     * The meta object literal for the '<em><b>Comparison color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE_MARK_SLOT__COMPARISON_COLOR = eINSTANCE.getStorageMarkSlot_Comparison_color();

    /**
     * The meta object literal for the '<em><b>Comparison int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE_MARK_SLOT__COMPARISON_INT = eINSTANCE.getStorageMarkSlot_Comparison_int();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE_MARK_SLOT__QUANTITY = eINSTANCE.getStorageMarkSlot_Quantity();

    /**
     * The meta object literal for the '<em><b>Measure</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE_MARK_SLOT__MEASURE = eINSTANCE.getStorageMarkSlot_Measure();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.CameraScanImpl <em>Camera Scan</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.CameraScanImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCameraScan()
     * @generated
     */
    EClass CAMERA_SCAN = eINSTANCE.getCameraScan();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMERA_SCAN__DEVICE = eINSTANCE.getCameraScan_Device();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMERA_SCAN__NAME = eINSTANCE.getCameraScan_Name();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.CranePickupImpl <em>Crane Pickup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.CranePickupImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCranePickup()
     * @generated
     */
    EClass CRANE_PICKUP = eINSTANCE.getCranePickup();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRANE_PICKUP__DEVICE = eINSTANCE.getCranePickup_Device();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRANE_PICKUP__LOCATION = eINSTANCE.getCranePickup_Location();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.impl.CraneDropImpl <em>Crane Drop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.impl.CraneDropImpl
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCraneDrop()
     * @generated
     */
    EClass CRANE_DROP = eINSTANCE.getCraneDrop();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRANE_DROP__DEVICE = eINSTANCE.getCraneDrop_Device();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRANE_DROP__LOCATION = eINSTANCE.getCraneDrop_Location();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.COLOR <em>COLOR</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.COLOR
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCOLOR()
     * @generated
     */
    EEnum COLOR = eINSTANCE.getCOLOR();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.CONST_VARIABLES <em>CONST VARIABLES</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.CONST_VARIABLES
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getCONST_VARIABLES()
     * @generated
     */
    EEnum CONST_VARIABLES = eINSTANCE.getCONST_VARIABLES();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.BOOLEAN_OPERATOR <em>BOOLEAN OPERATOR</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.BOOLEAN_OPERATOR
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getBOOLEAN_OPERATOR()
     * @generated
     */
    EEnum BOOLEAN_OPERATOR = eINSTANCE.getBOOLEAN_OPERATOR();

    /**
     * The meta object literal for the '{@link xtext.factoryLogicLang.TIME <em>TIME</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLogicLang.TIME
     * @see xtext.factoryLogicLang.impl.FactoryLogicLangPackageImpl#getTIME()
     * @generated
     */
    EEnum TIME = eINSTANCE.getTIME();

  }

} //FactoryLogicLangPackage
