/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLogicLang.Loop#getName <em>Name</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.Loop#getList <em>List</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.Loop#getSource <em>Source</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.Loop#getOperator <em>Operator</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.Loop#getComparison_const <em>Comparison const</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.Loop#getComparison_color <em>Comparison color</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.Loop#getComparison_int <em>Comparison int</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.Loop#getLogics <em>Logics</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getLoop()
 * @model
 * @generated
 */
public interface Loop extends Logic
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getLoop_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.Loop#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' attribute.
   * @see #setList(String)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getLoop_List()
   * @model
   * @generated
   */
  String getList();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.Loop#getList <em>List</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' attribute.
   * @see #getList()
   * @generated
   */
  void setList(String value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(Device)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getLoop_Source()
   * @model
   * @generated
   */
  Device getSource();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.Loop#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Device value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.factoryLogicLang.BOOLEAN_OPERATOR}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see xtext.factoryLogicLang.BOOLEAN_OPERATOR
   * @see #setOperator(BOOLEAN_OPERATOR)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getLoop_Operator()
   * @model
   * @generated
   */
  BOOLEAN_OPERATOR getOperator();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.Loop#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see xtext.factoryLogicLang.BOOLEAN_OPERATOR
   * @see #getOperator()
   * @generated
   */
  void setOperator(BOOLEAN_OPERATOR value);

  /**
   * Returns the value of the '<em><b>Comparison const</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.factoryLogicLang.CONST_VARIABLES}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparison const</em>' attribute.
   * @see xtext.factoryLogicLang.CONST_VARIABLES
   * @see #setComparison_const(CONST_VARIABLES)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getLoop_Comparison_const()
   * @model
   * @generated
   */
  CONST_VARIABLES getComparison_const();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.Loop#getComparison_const <em>Comparison const</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparison const</em>' attribute.
   * @see xtext.factoryLogicLang.CONST_VARIABLES
   * @see #getComparison_const()
   * @generated
   */
  void setComparison_const(CONST_VARIABLES value);

  /**
   * Returns the value of the '<em><b>Comparison color</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.factoryLogicLang.COLOR}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparison color</em>' attribute.
   * @see xtext.factoryLogicLang.COLOR
   * @see #setComparison_color(COLOR)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getLoop_Comparison_color()
   * @model
   * @generated
   */
  COLOR getComparison_color();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.Loop#getComparison_color <em>Comparison color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparison color</em>' attribute.
   * @see xtext.factoryLogicLang.COLOR
   * @see #getComparison_color()
   * @generated
   */
  void setComparison_color(COLOR value);

  /**
   * Returns the value of the '<em><b>Comparison int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparison int</em>' attribute.
   * @see #setComparison_int(int)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getLoop_Comparison_int()
   * @model
   * @generated
   */
  int getComparison_int();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.Loop#getComparison_int <em>Comparison int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparison int</em>' attribute.
   * @see #getComparison_int()
   * @generated
   */
  void setComparison_int(int value);

  /**
   * Returns the value of the '<em><b>Logics</b></em>' containment reference list.
   * The list contents are of type {@link xtext.factoryLogicLang.Logic}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logics</em>' containment reference list.
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getLoop_Logics()
   * @model containment="true"
   * @generated
   */
  EList<Logic> getLogics();

} // Loop
