/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.factoryLogicLang.FactoryLogicLangPackage;
import xtext.factoryLogicLang.StorageParameter;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Storage Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StorageParameterImpl extends MinimalEObjectImpl.Container implements StorageParameter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StorageParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FactoryLogicLangPackage.Literals.STORAGE_PARAMETER;
  }

} //StorageParameterImpl
