/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtext.factoryLogicLang.FactoryLogicLangPackage;
import xtext.factoryLogicLang.Loop;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Loop</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLogicLang.impl.LoopImpl#getLoopvar <em>Loopvar</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.impl.LoopImpl#getSTRING1 <em>STRING1</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.impl.LoopImpl#getSTRING2 <em>STRING2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LoopImpl extends DeclarationImpl implements Loop
{
  /**
   * The default value of the '{@link #getLoopvar() <em>Loopvar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoopvar()
   * @generated
   * @ordered
   */
  protected static final String LOOPVAR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLoopvar() <em>Loopvar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoopvar()
   * @generated
   * @ordered
   */
  protected String loopvar = LOOPVAR_EDEFAULT;

  /**
   * The default value of the '{@link #getSTRING1() <em>STRING1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSTRING1()
   * @generated
   * @ordered
   */
  protected static final String STRING1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSTRING1() <em>STRING1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSTRING1()
   * @generated
   * @ordered
   */
  protected String string1 = STRING1_EDEFAULT;

  /**
   * The default value of the '{@link #getSTRING2() <em>STRING2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSTRING2()
   * @generated
   * @ordered
   */
  protected static final String STRING2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSTRING2() <em>STRING2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSTRING2()
   * @generated
   * @ordered
   */
  protected String string2 = STRING2_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LoopImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FactoryLogicLangPackage.Literals.LOOP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLoopvar()
  {
    return loopvar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLoopvar(String newLoopvar)
  {
    String oldLoopvar = loopvar;
    loopvar = newLoopvar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FactoryLogicLangPackage.LOOP__LOOPVAR, oldLoopvar, loopvar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSTRING1()
  {
    return string1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSTRING1(String newSTRING1)
  {
    String oldSTRING1 = string1;
    string1 = newSTRING1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FactoryLogicLangPackage.LOOP__STRING1, oldSTRING1, string1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSTRING2()
  {
    return string2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSTRING2(String newSTRING2)
  {
    String oldSTRING2 = string2;
    string2 = newSTRING2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FactoryLogicLangPackage.LOOP__STRING2, oldSTRING2, string2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FactoryLogicLangPackage.LOOP__LOOPVAR:
        return getLoopvar();
      case FactoryLogicLangPackage.LOOP__STRING1:
        return getSTRING1();
      case FactoryLogicLangPackage.LOOP__STRING2:
        return getSTRING2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FactoryLogicLangPackage.LOOP__LOOPVAR:
        setLoopvar((String)newValue);
        return;
      case FactoryLogicLangPackage.LOOP__STRING1:
        setSTRING1((String)newValue);
        return;
      case FactoryLogicLangPackage.LOOP__STRING2:
        setSTRING2((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FactoryLogicLangPackage.LOOP__LOOPVAR:
        setLoopvar(LOOPVAR_EDEFAULT);
        return;
      case FactoryLogicLangPackage.LOOP__STRING1:
        setSTRING1(STRING1_EDEFAULT);
        return;
      case FactoryLogicLangPackage.LOOP__STRING2:
        setSTRING2(STRING2_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FactoryLogicLangPackage.LOOP__LOOPVAR:
        return LOOPVAR_EDEFAULT == null ? loopvar != null : !LOOPVAR_EDEFAULT.equals(loopvar);
      case FactoryLogicLangPackage.LOOP__STRING1:
        return STRING1_EDEFAULT == null ? string1 != null : !STRING1_EDEFAULT.equals(string1);
      case FactoryLogicLangPackage.LOOP__STRING2:
        return STRING2_EDEFAULT == null ? string2 != null : !STRING2_EDEFAULT.equals(string2);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (loopvar: ");
    result.append(loopvar);
    result.append(", STRING1: ");
    result.append(string1);
    result.append(", STRING2: ");
    result.append(string2);
    result.append(')');
    return result.toString();
  }

} //LoopImpl
