/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Camera Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLogicLang.CameraParameter#getColor <em>Color</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getCameraParameter()
 * @model
 * @generated
 */
public interface CameraParameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.factoryLogicLang.COLOR}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see xtext.factoryLogicLang.COLOR
   * @see #setColor(COLOR)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getCameraParameter_Color()
   * @model
   * @generated
   */
  COLOR getColor();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.CameraParameter#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see xtext.factoryLogicLang.COLOR
   * @see #getColor()
   * @generated
   */
  void setColor(COLOR value);

} // CameraParameter
