/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Crane Drop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLogicLang.CraneDrop#getDevice <em>Device</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.CraneDrop#getLocation <em>Location</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getCraneDrop()
 * @model
 * @generated
 */
public interface CraneDrop extends Operation
{
  /**
   * Returns the value of the '<em><b>Device</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device</em>' reference.
   * @see #setDevice(Crane)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getCraneDrop_Device()
   * @model
   * @generated
   */
  Crane getDevice();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.CraneDrop#getDevice <em>Device</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Device</em>' reference.
   * @see #getDevice()
   * @generated
   */
  void setDevice(Crane value);

  /**
   * Returns the value of the '<em><b>Location</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' reference.
   * @see #setLocation(CraneParameter)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getCraneDrop_Location()
   * @model
   * @generated
   */
  CraneParameter getLocation();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.CraneDrop#getLocation <em>Location</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location</em>' reference.
   * @see #getLocation()
   * @generated
   */
  void setLocation(CraneParameter value);

} // CraneDrop
