/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Crane Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLogicLang.CraneParameter#getDegree <em>Degree</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.CraneParameter#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getCraneParameter()
 * @model
 * @generated
 */
public interface CraneParameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Degree</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Degree</em>' attribute.
   * @see #setDegree(int)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getCraneParameter_Degree()
   * @model
   * @generated
   */
  int getDegree();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.CraneParameter#getDegree <em>Degree</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Degree</em>' attribute.
   * @see #getDegree()
   * @generated
   */
  void setDegree(int value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getCraneParameter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.CraneParameter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // CraneParameter
