/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends Logic
{
} // Operation
