/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Storage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLogicLang.Storage#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorage()
 * @model
 * @generated
 */
public interface Storage extends Device
{
  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link xtext.factoryLogicLang.StorageParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorage_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<StorageParameter> getParameters();

} // Storage
