/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Storage Mark Slot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLogicLang.StorageMarkSlot#getDevice <em>Device</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.StorageMarkSlot#getPosition <em>Position</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.StorageMarkSlot#getComparison_const <em>Comparison const</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.StorageMarkSlot#getComparison_color <em>Comparison color</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.StorageMarkSlot#getComparison_int <em>Comparison int</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.StorageMarkSlot#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.StorageMarkSlot#getMeasure <em>Measure</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorageMarkSlot()
 * @model
 * @generated
 */
public interface StorageMarkSlot extends Operation
{
  /**
   * Returns the value of the '<em><b>Device</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device</em>' reference.
   * @see #setDevice(Storage)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorageMarkSlot_Device()
   * @model
   * @generated
   */
  Storage getDevice();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.StorageMarkSlot#getDevice <em>Device</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Device</em>' reference.
   * @see #getDevice()
   * @generated
   */
  void setDevice(Storage value);

  /**
   * Returns the value of the '<em><b>Position</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Position</em>' reference.
   * @see #setPosition(StoragePositionParameter)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorageMarkSlot_Position()
   * @model
   * @generated
   */
  StoragePositionParameter getPosition();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.StorageMarkSlot#getPosition <em>Position</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Position</em>' reference.
   * @see #getPosition()
   * @generated
   */
  void setPosition(StoragePositionParameter value);

  /**
   * Returns the value of the '<em><b>Comparison const</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.factoryLogicLang.CONST_VARIABLES}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparison const</em>' attribute.
   * @see xtext.factoryLogicLang.CONST_VARIABLES
   * @see #setComparison_const(CONST_VARIABLES)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorageMarkSlot_Comparison_const()
   * @model
   * @generated
   */
  CONST_VARIABLES getComparison_const();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.StorageMarkSlot#getComparison_const <em>Comparison const</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparison const</em>' attribute.
   * @see xtext.factoryLogicLang.CONST_VARIABLES
   * @see #getComparison_const()
   * @generated
   */
  void setComparison_const(CONST_VARIABLES value);

  /**
   * Returns the value of the '<em><b>Comparison color</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.factoryLogicLang.COLOR}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparison color</em>' attribute.
   * @see xtext.factoryLogicLang.COLOR
   * @see #setComparison_color(COLOR)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorageMarkSlot_Comparison_color()
   * @model
   * @generated
   */
  COLOR getComparison_color();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.StorageMarkSlot#getComparison_color <em>Comparison color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparison color</em>' attribute.
   * @see xtext.factoryLogicLang.COLOR
   * @see #getComparison_color()
   * @generated
   */
  void setComparison_color(COLOR value);

  /**
   * Returns the value of the '<em><b>Comparison int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparison int</em>' attribute.
   * @see #setComparison_int(int)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorageMarkSlot_Comparison_int()
   * @model
   * @generated
   */
  int getComparison_int();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.StorageMarkSlot#getComparison_int <em>Comparison int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparison int</em>' attribute.
   * @see #getComparison_int()
   * @generated
   */
  void setComparison_int(int value);

  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorageMarkSlot_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.StorageMarkSlot#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

  /**
   * Returns the value of the '<em><b>Measure</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.factoryLogicLang.TIME}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Measure</em>' attribute.
   * @see xtext.factoryLogicLang.TIME
   * @see #setMeasure(TIME)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorageMarkSlot_Measure()
   * @model
   * @generated
   */
  TIME getMeasure();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.StorageMarkSlot#getMeasure <em>Measure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Measure</em>' attribute.
   * @see xtext.factoryLogicLang.TIME
   * @see #getMeasure()
   * @generated
   */
  void setMeasure(TIME value);

} // StorageMarkSlot
