/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Storage Position Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLogicLang.StoragePositionParameter#getSlot <em>Slot</em>}</li>
 *   <li>{@link xtext.factoryLogicLang.StoragePositionParameter#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStoragePositionParameter()
 * @model
 * @generated
 */
public interface StoragePositionParameter extends StorageParameter
{
  /**
   * Returns the value of the '<em><b>Slot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slot</em>' attribute.
   * @see #setSlot(int)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStoragePositionParameter_Slot()
   * @model
   * @generated
   */
  int getSlot();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.StoragePositionParameter#getSlot <em>Slot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Slot</em>' attribute.
   * @see #getSlot()
   * @generated
   */
  void setSlot(int value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStoragePositionParameter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.factoryLogicLang.StoragePositionParameter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // StoragePositionParameter
