/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLogicLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Storage Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.factoryLogicLang.FactoryLogicLangPackage#getStorageParameter()
 * @model
 * @generated
 */
public interface StorageParameter extends EObject
{
} // StorageParameter
