@startuml
class Model {
    + configurations: Configuration
    + statement: Statement
}

class Configuration {
    + device: Device
}

class Statement
class Loop {
    + variable: Variable
    + source: Device
    + operator: string
    + target: VariableValue
    + statements: Statement
}
class Operation
class Conditional {
    + operator: string
    + statements: Statement
}
class VariableConditional

class Device {
    + name: string
    + parameters: Parameter
}
class Parameter
class Number {
    + value: int
}
class Crane
class CraneParameter {
    + degree: int
    + name: string
}
class CraneOperation {
    + device: Crane
    + target: CraneParameter
}
class CraneConditional {
    + source: Crane
    + target: CraneParameter
}

class Disk {
    + size: DiskParameter
}
class DiskParameter
class DiskSizeParameter {
    + size: int
}
class DiskSlotParameter {
    + size: int
}
class DiskZoneParameter {
    + zone: int
    + slot: int
    + name: string
}
class DiskConditional {
    + source: Disk
    + target: DiskStateValue
}
class DiskOperation {
    + device: Disk
    + variable: Variable
    + target: DiskSlotParameter
}
class DiskPositionParameter
class DiskSlotValue {
    + ref: GlobalVariable
}
class DiskStateValue {
    + value: DISK_STATES
}
class DiskSlotStateValue {
    + value: DISK_SLOT_STATES
}
class DiskMoveSlotOperation {
    + source: DiskZoneParameter
}
class DiskMoveEmptySlotOperation
class DiskMarkSlotOperation {
    + value: DiskSlotValue
    + quantity: int
    + measure: TIME
}

class Camera
class CameraColorParameter {
    + color: COLOR
}
class CameraOperation {
    + device: Camera
    + variable: Variable
}
class CameraConditional {
    + source: Camera
    + target: COLOR
}

class Variable {
    + name: string
}
class VariableValue
class VariableConditional {
    + source: Variable
    + comparison_operator: COMPARISON_OPERATOR
    + target: VariableValue
}
class GlobalVariable
class LocalVariable
class ColorValue {
    + value: COLOR
}

enum COMPARISON_OPERATOR {
    LESS_THAN
    GREATER_THAN
}
enum COLOR {
    RED
    GREEN
    BLUE
}
enum DISK_STATES {
    FULL
    EMPTY
}
enum DISK_SLOT_STATES {
    FREE
    IN_PROGRESS
    COMPLETE
}
enum TIME {
    SECONDS
    SECOND
    MINUTES
    MINUTE
    HOURS
    HOUR
}

' Model
Model *--> "1..*" Configuration
Model *--> "1..*" Statement



' Configuration
Configuration *--> "1" Device
' Configuration:Device
Device *--> "1..*" Parameter
' Configuration:Device:Disk
Disk --|> Device
Disk *--> "1" DiskParameter
DiskParameter --|> Parameter
DiskPositionParameter --|> DiskParameter
DiskSlotParameter --|> DiskParameter
DiskZoneParameter --|> DiskParameter

' Configuration:Device:Camera
Camera --|> Device
CameraParameter --|> Parameter
CameraColorParameter --|> CameraParameter
CameraColorParameter *--> "1" COLOR

' Configuration:Device:Crane
Crane --|> Device
CraneParameter --|> Parameter
' Statements
' Statements:Conditionals
Conditional --|> Statement
Conditional o--> "1..*" Statement

VariableConditional --|> Conditional

CraneConditional --|> Conditional
CraneConditional *--> "1" Crane
CraneConditional *--> "1" CraneParameter

DiskConditional --|> Conditional
DiskConditional o--> "1" Disk
DiskConditional *--> "1" DiskStateValue

CameraConditional --|> Conditional
CameraConditional o--> "1" Camera
CameraConditional *--> "1" COLOR

VariableConditional --|> Conditional
VariableConditional o--> "1" Variable
VariableConditional --> "0..1" COMPARISON_OPERATOR
VariableConditional *--> "1" VariableValue

' Statements:Operations
Operation --|> Statement

CraneOperation --|> Operation
CraneOperation *--> "1" Crane
CraneOperation *--> "1" CraneParameter

DiskOperation --|> Operation
DiskOperation *--> "1" Disk
DiskOperation *--> "1" Variable
DiskOperation *--> "1" DiskSlotParameter

CameraOperation --|> Operation
CameraOperation *--> "1" Camera
CameraOperation *--> "1" Variable

DiskMoveSlotOperation --|> DiskOperation
DiskMoveSlotOperation *--> "1" DiskZoneParameter

DiskMoveEmptySlotOperation --|> DiskOperation

DiskMarkSlotOperation --|> DiskOperation
DiskMarkSlotOperation o--> "1" DiskSlotValue
DiskMarkSlotOperation *--> "1" TIME

' Statements:Loops
Loop --|> Statement
Loop *--> "1" Variable
Loop *--> "1" Device 
Loop *--> "1" VariableValue
Loop *--> "1..*" Statement 

' Variables
LocalVariable --|> Variable
GlobalVariable --|> Variable

' Values
DiskSlotValue *--> "1" GlobalVariable
DiskStateValue --|> VariableValue
DiskStateValue o--> "1" DISK_STATES
DiskSlotStateValue --|> VariableValue
DiskSlotStateValue --|> DiskSlotValue
DiskSlotStateValue o--> "1" DISK_SLOT_STATES
ColorValue --|> VariableValue
ColorValue --|> DiskSlotValue
ColorValue o--> "1" COLOR
Number --|> VariableValue

@enduml