/*
 * generated by Xtext 2.25.0
 */
package xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFactoryLogicLangScopeProvider extends DelegatingScopeProvider {
}
